# Generated by Django 4.2.7 on 2025-12-16 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='price_cents',
            new_name='price_egp',
        ),
    ]
