# Generated by Django 5.2.9 on 2025-12-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_rename_price_cents_menuitem_price_egp"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="sizes",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
